In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [ ]:
data = pd.read_csv('Ressources/accidents_2024.csv')
print(data.head())

        Num_Acc  jour  mois    an   hrmn  lum dep    com  agg  int  atm  col  \
0  202400000001    25     3  2024  07:40    2  70  70285    1    1    5    1
1  202400000002    20     3  2024  15:05    1  21  21054    2    3    7    6
2  202400000003    22     3  2024  19:30    2  15  15012    1    1    1    6
3  202400000004    24     3  2024  17:50    1  14  14118    2    3    7    3
4  202400000005    25     3  2024  19:35    5  13  13106    1    3    2    5

           lat          long  Nb_victimes     saison           nom_dep  \
0  47,56277000    6,75832000            1  Printemps       Haute-Saône
1  47,02109000    4,83755000            1  Printemps         Côte-d'Or
2  44,90238400    2,49641800            4  Printemps            Cantal
3  49,19166000   -0,39851000            1  Printemps          Calvados
4  43,39000000    5,35000000            3  Printemps  Bouches-du-Rhône

   population        date jour_semaine
0    234296.0  2024-03-25        Lundi
1    535503.0  2024-03-20     Mercredi
2    144226.0  2024-03-22     Vendredi
3    700633.0  2024-03-24     Dimanche
4   2056943.0  2024-03-25        Lundi

,Num_Acc,jour,mois,an,hrmn,lum,dep,com,agg,int,atm,col,lat,long,Nb_victimes,saison,nom_dep,population,date,jour_semaine
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54391,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
54392,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
54393,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
54394,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
54395,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [21]:
data.isna().sum()

Num_Acc         0
jour            0
mois            0
an              0
hrmn            0
lum             0
dep             0
com             0
agg             0
int             0
atm             0
col             0
lat             0
long            0
Nb_victimes     0
saison          0
date            0
jour_semaine    0
dtype: int64

In [23]:
data_copy = data.copy()

In [32]:
data.shape

(54396, 18)

In [33]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 54396 entries, 0 to 54395
Data columns (total 18 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Num_Acc       54396 non-null  int64
 1   jour          54396 non-null  int64
 2   mois          54396 non-null  int64
 3   an            54396 non-null  int64
 4   hrmn          54396 non-null  str
 5   lum           54396 non-null  int64
 6   dep           54396 non-null  str
 7   com           54396 non-null  str
 8   agg           54396 non-null  int64
 9   int           54396 non-null  int64
 10  atm           54396 non-null  int64
 11  col           54396 non-null  int64
 12  lat           54396 non-null  str
 13  long          54396 non-null  str
 14  Nb_victimes   54396 non-null  int64
 15  saison        54396 non-null  str
 16  date          54396 non-null  str
 17  jour_semaine  54396 non-null  str
dtypes: int64(10), str(8)
memory usage: 7.5 MB

In [34]:
data.describe()

,Num_Acc,jour,mois,an,lum,agg,int,atm,col,Nb_victimes
count,5.439600e+04,54396.000000,54396.000000,54396.0,54396.000000,54396.000000,54396.000000,54396.000000,54396.000000,54396.000000
mean,2.024000e+11,15.665067,6.615836,2024.0,1.949665,1.625119,2.108243,1.677550,4.018623,1.328407
std,1.570466e+04,8.737628,3.361617,0.0,1.488407,0.484096,2.042686,1.737039,1.983970,0.849383
min,2.024000e+11,1.000000,1.000000,2024.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,2.024000e+11,8.000000,4.000000,2024.0,1.000000,1.000000,1.000000,1.000000,3.000000,1.000000
50%,2.024000e+11,16.000000,7.000000,2024.0,1.000000,2.000000,1.000000,1.000000,3.000000,1.000000
75%,2.024000e+11,23.000000,10.000000,2024.0,3.000000,2.000000,2.000000,1.000000,6.000000,1.000000
max,2.024001e+11,31.000000,12.000000,2024.0,5.000000,2.000000,9.000000,9.000000,7.000000,50.000000