In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder

In [2]:
data = pd.read_csv('Ressources/accidents_2024.csv')
print(data.head())

        Num_Acc  jour  mois    an   hrmn  lum dep    com  agg  int  atm  col  \
0  202400000001    25     3  2024  07:40    2  70  70285    1    1    5    1
1  202400000002    20     3  2024  15:05    1  21  21054    2    3    7    6
2  202400000003    22     3  2024  19:30    2  15  15012    1    1    1    6
3  202400000004    24     3  2024  17:50    1  14  14118    2    3    7    3
4  202400000005    25     3  2024  19:35    5  13  13106    1    3    2    5

           lat          long  Nb_victimes     saison           nom_dep  \
0  47,56277000    6,75832000            1  Printemps       Haute-Saône
1  47,02109000    4,83755000            1  Printemps         Côte-d'Or
2  44,90238400    2,49641800            4  Printemps            Cantal
3  49,19166000   -0,39851000            1  Printemps          Calvados
4  43,39000000    5,35000000            3  Printemps  Bouches-du-Rhône

   population        date jour_semaine
0    234296.0  2024-03-25        Lundi
1    535503.0  2024-03-20     Mercredi
2    144226.0  2024-03-22     Vendredi
3    700633.0  2024-03-24     Dimanche
4   2056943.0  2024-03-25        Lundi

In [3]:
data.isna().sum()

Num_Acc            0
jour               0
mois               0
an                 0
hrmn               0
lum                0
dep                0
com                0
agg                0
int                0
atm                0
col                0
lat                0
long               0
Nb_victimes        0
saison             0
nom_dep         3230
population      3230
date               0
jour_semaine       0
dtype: int64

In [4]:
data.shape

(54396, 20)

In [5]:
data.describe()

,Num_Acc,jour,mois,an,lum,agg,int,atm,col,Nb_victimes,population
count,5.439600e+04,54396.000000,54396.000000,54396.0,54396.000000,54396.000000,54396.000000,54396.000000,54396.000000,54396.000000,5.116600e+04
mean,2.024000e+11,15.665067,6.615836,2024.0,1.949665,1.625119,2.108243,1.677550,4.018623,1.328407,1.147967e+06
std,1.570466e+04,8.737628,3.361617,0.0,1.488407,0.484096,2.042686,1.737039,1.983970,0.849383,6.360300e+05
min,2.024000e+11,1.000000,1.000000,2024.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,7.651900e+04
25%,2.024000e+11,8.000000,4.000000,2024.0,1.000000,1.000000,1.000000,1.000000,3.000000,1.000000,5.662520e+05
50%,2.024000e+11,16.000000,7.000000,2024.0,1.000000,2.000000,1.000000,1.000000,3.000000,1.000000,1.152662e+06
75%,2.024000e+11,23.000000,10.000000,2024.0,3.000000,2.000000,2.000000,1.000000,6.000000,1.000000,1.654970e+06
max,2.024001e+11,31.000000,12.000000,2024.0,5.000000,2.000000,9.000000,9.000000,7.000000,50.000000,2.611293e+06

In [6]:
data_copy = data.copy()

In [7]:
data_copy = data_copy.drop(columns = ["Num_Acc", "population", "nom_dep"])

In [8]:
data_copy.head()

,jour,mois,an,hrmn,lum,dep,com,agg,int,atm,col,lat,long,Nb_victimes,saison,date,jour_semaine
0,25,3,2024,07:40,2,70,70285,1,1,5,1,"47,56277000","6,75832000",1,Printemps,2024-03-25,Lundi
1,20,3,2024,15:05,1,21,21054,2,3,7,6,"47,02109000","4,83755000",1,Printemps,2024-03-20,Mercredi
2,22,3,2024,19:30,2,15,15012,1,1,1,6,"44,90238400","2,49641800",4,Printemps,2024-03-22,Vendredi
3,24,3,2024,17:50,1,14,14118,2,3,7,3,"49,19166000","-0,39851000",1,Printemps,2024-03-24,Dimanche
4,25,3,2024,19:35,5,13,13106,1,3,2,5,"43,39000000","5,35000000",3,Printemps,2024-03-25,Lundi

In [9]:
# 1. On extrait l'heure numérique (0 à 23)

data_copy['heure'] = pd.to_numeric(data_copy['hrmn'].str[:2], errors='coerce').fillna(12)

In [10]:
# 2. On encode le département en nombre de 0 a 100 (gère proprement 2A et 2B)

data_copy['dep_code'] = LabelEncoder().fit_transform(data_copy['dep'].astype(str))

In [11]:
X = data_copy.drop(columns = ["an", 'hrmn', 'dep', 'com', 'lat', 'long', 'Nb_victimes', 'saison', 'date', 'jour_semaine'])
X.head()

   jour  mois  lum  agg  int  atm  col  heure  dep_code
0    25     3    2    1    1    5    1      7        70
1    20     3    1    2    3    7    6     15        19
2    22     3    2    1    1    1    6     19        14
3    24     3    1    2    3    7    3     17        13
4    25     3    5    1    3    2    5     19        12

In [12]:
Y = data_copy["Nb_victimes"]

In [13]:
X_train, X_test, Y_train, Y_test = train_test_split(
    X,
    Y,
    test_size = 0.2
)

In [14]:
print("X_train :", X_train.shape)
print("X_test  :", X_test.shape)
print("y_train :", Y_train.shape)
print("y_test  :", Y_test.shape)

X_train : (43516, 9)
X_test  : (10880, 9)
y_train : (43516,)
y_test  : (10880,)

In [15]:
scaler = StandardScaler()

In [16]:
X_train_scaled = scaler.fit_transform(X_train)

In [17]:
X_test_scaled = scaler.transform(X_test)

In [18]:
#modele KNN
knn = KNeighborsClassifier(n_neighbors = 5, weights = 'distance')

In [19]:
knn.fit(X_train_scaled, Y_train)

KNeighborsClassifier(weights='distance')

In [20]:
Y_pred = knn.predict (X_test_scaled)

In [21]:
Y_pred[:1000]

array([1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 4, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2,
       1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1,
       2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 6, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1,
       1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 3, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1, 1, 1, 1,
       1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 4, 1, 2, 2, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
       2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1,
       1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [22]:
comparaison  = pd.DataFrame({
    "Nb de victime reel" : Y_test.values,
    "Nb de victime predit" : Y_pred
})

comparaison.head(50)

    Nb de victime reel  Nb de victime predit
0                    1                     1
1                    2                     1
2                    1                     1
3                    2                     2
4                    1                     1
5                    2                     1
6                    5                     1
7                    1                     1
8                    1                     1
9                    1                     2
10                   6                     1
11                   1                     1
12                   3                     1
13                   2                     1
14                   1                     1
15                   1                     3
16                   1                     1
17                   1                     1
18                   1                     1
19                   1                     1
20                   2                     1
21                   1                     1
22                   1                     1
23                   2                     1
24                   2                     1
25                   1                     1
26                   1                     1
27                   2                     1
28                   2                     1
29                   1                     1
30                   1                     1
31                   1                     1
32                   3                     1
33                   3                     1
34                   5                     1
35                   1                     1
36                   1                     1
37                   1                     2
38                   1                     1
39                   2                     2
40                   1                     1
41                   1                     1
42                   1                     1
43                   1                     1
44                   1                     1
45                   1                     1
46                   1                     1
47                   1                     1
48                   1                     1
49                   1                     1